Initial commit from Create Next App
ADMIN@DESKTOP-2EKQ2CG MINGW64 ~/portfolio (main)
$ git push -u origin main
To https://github.com/jobrian-coder/portfolio.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/jobrian-coder/portfolio.git'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

ADMIN@DESKTOP-2EKQ2CG MINGW64 ~/portfolio (main)
$ git pull origin main --rebase
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (6/6), 1.76 KiB | 78.00 KiB/s, done.
From https://github.com/jobrian-coder/portfolio
 * branch            main       -> FETCH_HEAD
 * [new branch]      main       -> origin/main
Auto-merging README.md
CONFLICT (add/add): Merge conflict in README.md
error: could not apply e4dbf0a... Initial commit from Create Next App
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
Could not apply e4dbf0a... # Initial commit from Create Next App